language: node_js
node_js:
    - 10
install:
    - npm ci

jobs:
    include:
        - script: echo "npm test temporarily disabled"
        - stage: lint-src
          script: npm run lint:src
        - stage: typecheck-src
          script: npm run typecheck:src

stages:
    - lint-src
    - typecheck-src
